#!/usr/bin/env python3
"""
Windows Build Script for node3 Agent
=====================================

Creates a Windows executable and NSIS installer.

Requirements:
- PyInstaller: pip install pyinstaller
- NSIS: Download from https://nsis.sourceforge.io/

Usage:
    python build_windows.py
    python build_windows.py --no-installer  # Skip NSIS installer creation
"""

import os
import sys
import subprocess
import shutil
from pathlib import Path

def print_step(msg):
    print(f"\n{'='*60}")
    print(f"  {msg}")
    print(f"{'='*60}\n")

def get_version():
    """Extract version from main.py"""
    try:
        with open('main.py', 'r') as f:
            content = f.read()
            import re
            match = re.search(r'VERSION\s*=\s*["\']([^"\']+)["\']', content)
            return match.group(1) if match else '1.0.0'
    except:
        return '1.0.0'

def clean_build():
    """Remove previous build artifacts"""
    print_step("Cleaning previous builds")
    
    dirs_to_remove = ['build', 'dist']
    for dir_name in dirs_to_remove:
        if os.path.exists(dir_name):
            shutil.rmtree(dir_name)
            print(f"✓ Removed {dir_name}/")
    
    # Remove spec files
    for spec_file in Path('.').glob('*.spec'):
        spec_file.unlink()
        print(f"✓ Removed {spec_file}")

def build_executable():
    """Build Windows executable with PyInstaller"""
    print_step("Building Windows executable")
    
    # Check PyInstaller
    try:
        subprocess.run(['pyinstaller', '--version'], 
                      capture_output=True, check=True)
    except:
        print("❌ PyInstaller not found!")
        print("Install with: pip install pyinstaller")
        return False
    
    # Build command
    cmd = [
        'pyinstaller',
        '--name=node3-agent',
        '--onefile',
        '--windowed',
        '--icon=icon.ico',  # Windows uses .ico
        '--add-data=templates;templates',
        '--additional-hooks-dir=.',  # Use our custom hooks to override torch
        
        # Hidden imports
        '--hidden-import=uvicorn.logging',
        '--hidden-import=uvicorn.loops',
        '--hidden-import=uvicorn.loops.auto',
        '--hidden-import=uvicorn.protocols',
        '--hidden-import=uvicorn.protocols.http',
        '--hidden-import=uvicorn.protocols.http.auto',
        '--hidden-import=uvicorn.protocols.websockets',
        '--hidden-import=uvicorn.protocols.websockets.auto',
        '--hidden-import=uvicorn.lifespan',
        '--hidden-import=uvicorn.lifespan.on',
        '--collect-all=fastapi',
        '--collect-all=pydantic',
        
        # Exclude unused modules
        # Aggressively exclude ML frameworks and their dependencies
        '--exclude-module=torch',
        '--exclude-module=torch.utils',
        '--exclude-module=torch.utils.tensorboard',
        '--exclude-module=tensorflow',
        '--exclude-module=matplotlib',
        '--exclude-module=numpy',
        '--exclude-module=pandas',
        '--exclude-module=scipy',
        '--exclude-module=IPython',
        '--exclude-module=jupyter',
        '--exclude-module=notebook',
        '--exclude-module=tkinter',
        '--exclude-module=PyQt5',
        '--exclude-module=PyQt6',
        '--exclude-module=PySide2',
        '--exclude-module=PySide6',
        '--exclude-module=pytest',
        '--exclude-module=tensorboard',
        
        '--strip',
        '--clean',
        'main.py'
    ]
    
    # Import PyInstaller API to run in same process (so recursion limit takes effect)
    try:
        import PyInstaller.__main__  # type: ignore
    except ImportError:
        print("❌ PyInstaller not found. Install with: pip install pyinstaller")
        return False
    
    print("Building with PyInstaller...")
    # Increase recursion limit and run PyInstaller
    sys.setrecursionlimit(3000)  # Handle deep import chains during analysis
    try:
        PyInstaller.__main__.run(cmd[1:])
        returncode = 0
    except SystemExit as e:
        returncode = e.code if e.code else 0
    
    if returncode == 0:
        print("\n✓ Executable built successfully!")
        
        # Get file size
        exe_path = Path('dist') / 'node3-agent.exe'
        if exe_path.exists():
            size_mb = exe_path.stat().st_size / (1024 * 1024)
            print(f"✓ Size: {size_mb:.1f} MB")
            print(f"✓ Location: {exe_path}")
        return True
    else:
        print("\n❌ Build failed!")
        return False

def create_nsis_script(version):
    """Create NSIS installer script"""
    script = f'''
; node3 Agent NSIS Installer Script
; Generated by build_windows.py

!include "MUI2.nsh"

; App Info
Name "node3 Agent"
OutFile "node3-agent-{version}-windows-setup.exe"
InstallDir "$PROGRAMFILES64\\node3-agent"
RequestExecutionLevel admin

; Interface Settings
!define MUI_ABORTWARNING
!define MUI_ICON "icon.ico"

; Pages
!insertmacro MUI_PAGE_LICENSE "LICENSE"
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

; Languages
!insertmacro MUI_LANGUAGE "English"

; Installer Sections
Section "Install"
    SetOutPath "$INSTDIR"
    
    ; Copy files
    File "dist\\node3-agent.exe"
    File "README.md"
    
    ; Create shortcuts
    CreateDirectory "$SMPROGRAMS\\node3 Agent"
    CreateShortcut "$SMPROGRAMS\\node3 Agent\\node3 Agent.lnk" "$INSTDIR\\node3-agent.exe"
    CreateShortcut "$SMPROGRAMS\\node3 Agent\\Uninstall.lnk" "$INSTDIR\\Uninstall.exe"
    CreateShortcut "$DESKTOP\\node3 Agent.lnk" "$INSTDIR\\node3-agent.exe"
    
    ; Write uninstaller
    WriteUninstaller "$INSTDIR\\Uninstall.exe"
    
    ; Registry info for Add/Remove Programs
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\node3Agent" "DisplayName" "node3 Agent"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\node3Agent" "UninstallString" "$INSTDIR\\Uninstall.exe"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\node3Agent" "DisplayVersion" "{version}"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\node3Agent" "Publisher" "node3"
SectionEnd

; Uninstaller Section
Section "Uninstall"
    ; Remove files
    Delete "$INSTDIR\\node3-agent.exe"
    Delete "$INSTDIR\\README.md"
    Delete "$INSTDIR\\Uninstall.exe"
    RMDir "$INSTDIR"
    
    ; Remove shortcuts
    Delete "$SMPROGRAMS\\node3 Agent\\node3 Agent.lnk"
    Delete "$SMPROGRAMS\\node3 Agent\\Uninstall.lnk"
    Delete "$DESKTOP\\node3 Agent.lnk"
    RMDir "$SMPROGRAMS\\node3 Agent"
    
    ; Remove registry keys
    DeleteRegKey HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\node3Agent"
SectionEnd
'''
    
    with open('node3-setup.nsi', 'w') as f:
        f.write(script)
    
    print("✓ Created NSIS script: node3-setup.nsi")

def build_installer(version):
    """Build NSIS installer"""
    print_step("Building Windows installer")
    
    # Check if NSIS is available
    makensis_paths = [
        'makensis',  # If in PATH
        'C:\\Program Files (x86)\\NSIS\\makensis.exe',
        'C:\\Program Files\\NSIS\\makensis.exe',
    ]
    
    makensis = None
    for path in makensis_paths:
        try:
            subprocess.run([path, '/VERSION'], 
                          capture_output=True, check=True)
            makensis = path
            break
        except:
            continue
    
    if not makensis:
        print("⚠️  NSIS not found - skipping installer creation")
        print("   Download from: https://nsis.sourceforge.io/")
        print(f"   Manual installer: Copy dist/node3-agent.exe to users")
        return False
    
    # Create NSIS script
    create_nsis_script(version)
    
    # Build installer
    print("Building installer with NSIS...")
    result = subprocess.run([makensis, 'node3-setup.nsi'])
    
    if result.returncode == 0:
        installer_name = f'node3-agent-{version}-windows-setup.exe'
        if Path(installer_name).exists():
            size_mb = Path(installer_name).stat().st_size / (1024 * 1024)
            print(f"\n✓ Installer created: {installer_name}")
            print(f"✓ Size: {size_mb:.1f} MB")
            return True
    
    print("\n❌ Installer build failed")
    return False

def main():
    import argparse
    parser = argparse.ArgumentParser(description='Build node3 Agent for Windows')
    parser.add_argument('--no-installer', action='store_true',
                       help='Skip NSIS installer creation')
    args = parser.parse_args()
    
    version = get_version()
    
    print("=" * 60)
    print(f"Building node3 Agent for Windows v{version}")
    print("=" * 60)
    print()
    
    # Step 1: Clean
    clean_build()
    
    # Step 2: Build executable
    if not build_executable():
        print("\n❌ Build failed!")
        sys.exit(1)
    
    # Step 3: Build installer (optional)
    if not args.no_installer:
        build_installer(version)
    
    # Summary
    print_step("Build Complete!")
    print(f"Version: {version}")
    print(f"Executable: dist/node3-agent.exe")
    
    if not args.no_installer:
        installer_name = f'node3-agent-{version}-windows-setup.exe'
        if Path(installer_name).exists():
            print(f"Installer: {installer_name}")
    
    print("\nTest the build:")
    print("  dist\\node3-agent.exe")
    print("\nDistribute:")
    if not args.no_installer:
        print(f"  {installer_name}")
    else:
        print("  dist/node3-agent.exe (standalone)")

if __name__ == '__main__':
    main()

